from datetime import date, datetime, timedelta
from itertools import islice
from pathlib import Path

import pandas as pd
from fastapi import HTTPException

from app.data.demo import get_profile, make_forecast


# Real model output generated by the GIS + downscaling pipeline
DATA_FILE = (
    Path(__file__).resolve().parents[2]
    / "data"
    / "processed"
    / "panchayat_polygon_rainfall_july2025_test.csv"
)


def _load_real_data() -> pd.DataFrame:
    """Load the final Panchayat-level rainfall predictions."""
    if not DATA_FILE.exists():
        raise RuntimeError(
            f"Real prediction file not found: {DATA_FILE}"
        )

    df = pd.read_csv(DATA_FILE)

    required_columns = {
        "date",
        "gpcode",
        "gpname",
        "district_code",
        "district",
        "block_code",
        "block",
        "final_rainfall_mm",
        "prediction_method",
    }

    missing = required_columns - set(df.columns)

    if missing:
        raise RuntimeError(
            f"Missing required columns in prediction file: {sorted(missing)}"
        )

    df["date"] = pd.to_datetime(df["date"]).dt.date

    return df


# Load once when the backend starts.
REAL_DATA = _load_real_data()
PANCHAYAT_NAMES = sorted(
    REAL_DATA["gpname"].dropna().astype(str).unique().tolist()
)


def get_panchayats(
    search: str = "", limit: int = 50, offset: int = 0
) -> list[str]:
    """Return one page of a case-insensitive Panchayat search."""
    query = search.strip().casefold()
    matches = (
        name for name in PANCHAYAT_NAMES
        if not query or query in name.casefold()
    )
    return list(islice(matches, offset, offset + limit))


def _find_panchayat(panchayat: str) -> pd.DataFrame:
    """Find a Panchayat by name, case-insensitively."""

    name = panchayat.strip().lower()

    matches = REAL_DATA[
        REAL_DATA["gpname"]
        .astype(str)
        .str.strip()
        .str.lower()
        == name
    ].copy()

    if matches.empty:
        raise HTTPException(
            status_code=404,
            detail=f"Panchayat '{panchayat}' not found in real prediction data.",
        )

    return matches.sort_values("date")


def _risk_from_rainfall(rainfall: float) -> str:
    """Simple demo risk classification based on rainfall amount."""

    if rainfall < 2.5:
        return "Low"

    if rainfall < 15:
        return "Medium"

    return "High"


def _condition_from_rainfall(rainfall: float) -> str:
    """Convert rainfall amount into a simple weather condition."""

    if rainfall < 0.1:
        return "Clear"

    if rainfall < 2.5:
        return "Light Rain"

    if rainfall < 15:
        return "Moderate Rain"

    return "Heavy Rain"


def _rain_probability_from_rainfall(rainfall: float) -> float:
    """
    Demo probability derived from the predicted rainfall amount.

    This is NOT an observed IMD probability forecast.
    It is only used to keep the current frontend/API structure working.
    """

    if rainfall < 0.1:
        return 10.0

    if rainfall < 2.5:
        return 40.0

    if rainfall < 15:
        return 70.0

    return 90.0


def get_weather(panchayat: str) -> dict:
    """
    Return current/latest real Panchayat rainfall prediction.

    Other weather fields are retained from the existing demo profile
    because the current real Panchayat output contains rainfall only.
    """

    data = _find_panchayat(panchayat)

    latest = data.iloc[-1]

    actual_name = str(latest["gpname"])
    rainfall = float(latest["final_rainfall_mm"])

    # Keep existing demo meteorological fields so the current frontend
    # continues to receive the expected response structure.
    try:
        profile = get_profile(actual_name)
    except Exception:
        profile = get_profile("Bara")

    risk = _risk_from_rainfall(rainfall)

    return {
        "panchayat": actual_name,
        "date": latest["date"],
        "rainfall": rainfall,
        "rainfall_range": (
            f"{max(0, rainfall - 4):.1f} - {rainfall + 6:.1f} mm"
        ),
        "max_temp": profile["max_temp"],
        "min_temp": profile["min_temp"],
        "humidity": profile["humidity"],
        "wind_speed": profile["wind_speed"],
        "wind_direction": profile["wind_direction"],
        "condition": _condition_from_rainfall(rainfall),
        "confidence": risk,
        "confidence_value": 85.0,
        "risk": risk,
        "risk_text": (
            "Low rainfall risk"
            if risk == "Low"
            else "Moderate rainfall risk"
            if risk == "Medium"
            else "High rainfall risk"
        ),
    }


def get_forecast(panchayat: str, days: int = 7) -> list[dict]:
    """
    Return real Panchayat-level rainfall predictions.

    Current generated dataset contains 5 test days:
    2025-07-27 to 2025-07-31.

    Other weather fields come from the existing demo profile so the
    current frontend remains compatible.
    """

    data = _find_panchayat(panchayat)

    # Only return the dates actually available in the real dataset.
    data = data.head(days)

    try:
        demo_forecast = make_forecast(panchayat, days=max(days, 5))
    except Exception:
        demo_forecast = make_forecast("Bara", days=max(days, 5))

    forecast = []

    for index, (_, row) in enumerate(data.iterrows()):

        rainfall = max(0.0, float(row["final_rainfall_mm"]))

        # Use demo values only for variables that are not yet present
        # in the final Panchayat rainfall dataset.
        if index < len(demo_forecast):
            demo_day = demo_forecast[index]
        else:
            demo_day = demo_forecast[-1]

        forecast_date = row["date"]

        forecast.append(
            {
                "date": forecast_date,
                "day": forecast_date.strftime("%A"),
                "rainfall": round(rainfall, 2),
                "rain_probability": _rain_probability_from_rainfall(
                    rainfall
                ),
                "max_temp": float(demo_day["max_temp"]),
                "min_temp": float(demo_day["min_temp"]),
                "humidity": float(demo_day["humidity"]),
                "wind_speed": float(demo_day["wind_speed"]),
                "condition": _condition_from_rainfall(rainfall),
            }
        )

    return forecast